#!/usr/bin/env expect  

set ip [lindex $argv 0 ]
set slot [lindex $argv 1]
set wld [lindex $argv 2]
set timeout -1
set node_ip $ip
if {[llength $argv] == 1} {
        spawn telnet 192.168.143.$node_ip 2023
        set node_spawn_id $spawn_id
        expect "login: "
        send "guest\r"
        expect "Password: "
        send "iltwat\r"
        expect "> "
        send "su\r"
        expect "Password: "
        send "swtn100tj\r"
        expect "# "
        send "route add default gw 192.168.143.1\r"
        expect "# "
        send "cat /usr/sbin/tejas/version.h\r"
        expect "# "
        send "cd \/etc\/tejas\/log\r"
        expect "# "

        #stty raw -echo
        #expect_after {
        #        -i $user_spawn_id
        #        "y" {send "rm -fr SysConf.* backconf.*\rcp defaultCfg\/* .\r"; exp_continue}
        #        "n" {send "\r\r"; exp_continue}
        #}
        #expect "> "
        #send "ls /usr/sbin/tejas | grep 'initialize.sh'
}

if {[llength $argv] == 2} {
spawn telnet 192.168.143.$node_ip 2023
#        spawn telnet 10.51.182.$node_ip 2023
       set node_spawn_id $spawn_id
        expect "login: "
       send "guest\r"
       expect "Password: "
       send "iltwat\r"
       expect "> "
       send "su\r"
       expect "Password: "
       send "swtn100tj\r"
       expect "# "
#       send "cd \/tmp\r"
#       expect "# "
#       send "rm *.hex\r"
#       expect "# "
#		send "ncftpget -uhexftp -piltwat 192.168.0.14 /tmp /home/hexftp/hex/mc/plc02/elk/fpga_edited/$wld\r"
#		expect "# "
       send "telnet 127.1.1.$slot 2023\r"
       expect "login: "
       send "guest\r"
       expect "Password: "
       send "iltwat\r"
       send "su\r"
       expect "Password: "
        send "swtn100tj\r"
       expect "# "
        send "cd \/etc\/tejas\/log\r"
        expect "# "
        send "export LD_LIBRARY_PATH=/usr/sbin/tejas/sharedobj\r"
#send "cd \/tmp\r"
#        expect "# "
#        send "ncftpget -uguest -piltwat 127.1.1.254 . /tmp/$wld\r"
#        expect "# "
#        send "mv $wld elk.hex\r"
#        expect "# "

 send "tail \-f *log00*\r"
     expect "# "
}

        interact

