#! /usr/bin/env expect

set ip [lindex $argv 0 ]
set slot [lindex $argv 1]
set timeout -1
set node_ip $ip
if {[llength $argv] == 1} {
        spawn telnet 192.168.241.$node_ip 2023
        set node_spawn_id $spawn_id
        expect "login: "
        send "guest\r"
        expect "Password: "
        send "iltwat\r"
        expect "> "
        send "su\r"
        expect "Password: "
        send "swtn100tj\r"
        expect "# "
        send "cat /usr/sbin/tejas/version.h\r"
        expect "# "
        send "cd \/etc\/tejas\/builds\/cef5\r"
        expect "# "
        send "uptime\r"
#       expect "# "
#		send "tail -f *log00*"

        #stty raw -echo
        #expect_after {
        #        -i $user_spawn_id
        #        "y" {send "rm -fr SysConf.* backconf.*\rcp defaultCfg\/* .\r"; exp_continue}
        #        "n" {send "\r\r"; exp_continue}
        #}
        #expect "> "
        #send "ls /usr/sbin/tejas | grep 'initialize.sh'
}
if {[llength $argv] == 2} {
        spawn telnet 192.168.241.$node_ip 2023
        set node_spawn_id $spawn_id
        expect "login: "
        send "guest\r"
        expect "Password: "
        send "iltwat\r"
        expect "> "
        send "su\r"
        expect "Password: "
        send "swtn100tj\r"
        expect "# "
        send "telnet 127.7.1.$slot 2023\r"
        expect "login: "
        send "guest\r"
        expect "Password: "
        send "iltwat\r"
        send "su\r"
        expect "Password: "
        send "swtn100tj\r"
        expect "# "
        send "export LD_LIBRARY_PATH=\/usr\/sbin\/tejas\/sharedobj\r"
        expect "# "
        send "cat /usr/sbin/tejas/version.h\r"
        expect "# "
        send "uptime\r"
       expect "# "
       send "cd \/etc\/tejas\/builds\/cef5\r"
       expect "# "
		send "tail -f \/etc\/tejas\/log\/*log00*\r"

# send "tail \-f *log00*\r"
#     expect "# "
 }

        interact

