#!/usr/bin/env expect 
##########################################################Generic Auto SSH (gas)###########################################################
if {[llength $argv] < 3} {
puts "\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\
\n               Usages: gat \[IP_or_IP_part\]   Username      Password\n 
\
\n               Node_IP : 102 will be treated as 192.168.230.102\
\n                         241.244 will be treated as 192.168.241.244\
\n                         169.200.100 will be treated as 192.169.200.100\
\n                         172.124.143.102 will be Taken as complete IP as it is given.\n
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n";
if {[llength $argv] < 3} { exit;
}
}
 # timeout -1 means infinite
    set timeout 300
    set ip_part [lindex $argv 0];
    set user [lindex $argv 1];
    set user_pass [lindex $argv 2];
    set su_user_pass [lindex $argv 3];
    set null_value "";

#flexible IP addressing
#So that u can provide 102 or 241.244 or 169.143.102 or 172.124.36.102 as IP.
    regexp "(\[0-9]{1,3})?\.?(\[0-9]{1,3})?\.?(\[0-9]{1,3})?\.?(\[0-9]{1,3})?" $ip_part all first second third fourth
if { $fourth != $null_value } {
   set ip "$all"
} elseif { $third != $null_value } {
   set ip "192\.$first\.$second\.$third"
} elseif { $second != $null_value } {
   set ip "192\.168\.$first\.$second"
} elseif { $first != $null_value } {
   set ip "192\.168\.230\.$first"
} else { puts "Invalid IP"; exit; }
puts "\nEntity IP is $ip \n"
spawn ssh $user@$ip -X
set node_spawn_id $spawn_id
expect {
	    "*yes/no*" {
			        send "yes\r"
			        exp_continue
				    }

	    "*asswor*" {
			        send "$user_pass\r"
				    }
}
if {[llength $argv] == 4} {
expect "*$*"
puts "Going for Super User Login"
send "su\r"
expect "*asswor*"
send "$su_user_pass\r"
interact
}
interact
