#!/usr/bin/perl

use HTTP::Request::Common qw(POST);
use LWP::UserAgent;
use LWP::Simple;
use HTML::Parser;

find_name(@ARGV); 

sub find_name() {
	$name = shift;
	$key = (shift or "name");
	$ua = new LWP::UserAgent;
	#my $url = 'http://postfix/cgi-bin/tejas/tis.cgi';
	my $url = 'http://192.168.0.8/cgi-bin/tejas/tis.cgi?action=searchUserInfo&key=name&keyval=';
	my $res = $ua->request(POST $url,
			[ action => searchUserInfo,
			keyval => $name,
			key => $key],
		      );

	if($res->is_success)  {
		#print $res->content;
		my $p = HTML::Parser->new(api_version => 3);
		$p->handler( start => \&start_handler, "tagname,self");
		$p->handler( end => \&end_handler, "tagname,self" );  
		$p->unbroken_text(1);
		print "\n";
		$p->parse($res->content) || die "Dieing $!"; 
		print "\n";

	} else {
		print "Error: " . $res->status_line . "\n";
	}                                                                                                                         
}

sub start_handler
{
        my $tag = shift;
        my $self = shift;
 
        if($tag eq "tr") { print "\n"; }
        elsif ($tag eq "td") {
                $self->handler(text => sub { my $t = shift; $t =~ s/\s+/ /g; print "$t\t"; }, "dtext");
        }
}

sub end_handler
{
        my $tag = shift;
        my $self = shift;
        if ($tag eq "td") { $self->handler(text => undef); }
}
